channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=24.3.1
- pip:
  - mlflow==2.20.0
  - cloudpickle==3.1.1
  - numpy==2.2.0
  - pandas==2.2.3
  - torch==2.5.1
  - tqdm==4.67.1
name: mlflow-env
